### ISSUE TITLE
One WebSocket between tabs

### ISSUE THREAD

**Issue by Shkarbatov** [halt-hammerzeit/shared_worker#1]
Hi, trying to understand:

    The second example shows how you can have only one websocket connection shared between multiple tabs.

adding:

    console.log(new Date().getTime());

before:

    webSocket = new WebSocket('ws://localhost:8888/')

And time always different, so always creates a new one WebSocket instance.
How I can be shure, that only one WebSocket used?

Thanks!

**Comment by halt-hammerzeit** [comment]
Hello.
This project hasn't been maintained for 4 years.
I haven't used it since.
